# 头部菜单，title: link
menu:
  Github: https://github.com/Singloo
  Twitter: https://twitter.com/Rickyan98932758

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3: 
  - https://timvel-1.oss-cn-hangzhou.aliyuncs.com/musics/organ_variation.mp3
  - https://timvel-1.oss-cn-hangzhou.aliyuncs.com/musics/space_song.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: https://source.unsplash.com/random/800x500

# 默认文章封面图
cover: https://source.unsplash.com/random/800x500

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: 'cc5fa8eb22be1b9c5beb'
    # 应用秘钥
    clientSecret: 'fc035ca7647676bfeda26468b449d13774ccb376'
    # issue仓库名
    repo: 'blog_gitalk'
    # Github名
    owner: 'Singloo'
    # Github名
    admin: ['Singloo']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: Timvel

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: UA-129908627-2

# 网站ico
favicon: /favicon.png

# rss文件
rss: atom.xml
